// Generated by deploy-backend.sh — do not edit manually.
export const AUTH_CONFIG = {
  cognitoDomain: 'https://writingworld-989593.auth.us-east-1.amazoncognito.com',
  clientId:      '40vjgj7av0s5tcaknfsp5lce4o',
  // Same-origin in production (/api/*); direct URL for localhost
  apiEndpoint:   window.location.hostname === 'localhost' ? 'https://c580nr4t9h.execute-api.us-east-1.amazonaws.com/api' : '/api',
  redirectUri:   window.location.origin + '/',
};
