// Generated by deploy-backend.sh — do not edit manually.
// Run ./infra/deploy.sh sync after this to push to S3.
export const AUTH_CONFIG = {
  cognitoDomain: 'https://writingworld-989593.auth.us-east-1.amazoncognito.com',
  clientId:      '40vjgj7av0s5tcaknfsp5lce4o',
  apiEndpoint:   window.location.hostname === 'localhost' ? 'https://c580nr4t9h.execute-api.us-east-1.amazonaws.com/api' : '/api',
  redirectUri:   window.location.origin + '/',
};
