// Generated by deploy-monitoring.sh — do not edit manually.
!function(n,i,v,r,s,c,u,x,z){x=window;z=document;u=z.createElement('script');
u.async=true;u.src=r;u.crossOrigin='anonymous';
z.head.insertBefore(u,z.head.firstElementChild);
x[n]=x[n]||{q:[]};x[n].q.push(i);
x[n][v]=function(){x[n].q.push([v].concat(Array.prototype.slice.call(arguments,0)))}}(
  'cwr', '776da356-f257-4d96-94d8-d1bf94b40895', 'recordEvent',
  'https://client.rum.us-east-1.amazonaws.com/1.x.x/cwr.js',
  {sessionSampleRate:1,
   guestRoleArn:"arn:aws:iam::920372989593:role/LoreRumGuestRole",
   identityPoolId:"us-east-1:26b6a51c-2e5c-4c6d-aad2-60a05d8545d7",
   endpoint:"https://dataplane.rum.us-east-1.amazonaws.com",
   telemetries:["errors","http","performance"],
   allowCookies:true,enableXRay:false}
);
