#!/usr/bin/env bash
# deploy-backend.sh — Deploy Writing World backend (Cognito + API + Lambda + Bedrock + DynamoDB)
# Usage: ./infra/deploy-backend.sh

set -euo pipefail

SCRIPT_DIR="$(dirname "$0")"
APP_DIR="$SCRIPT_DIR/.."

source "$SCRIPT_DIR/deploy.env"       # AWS_PROFILE
source "$SCRIPT_DIR/backend.env"      # COGNITO_DOMAIN_PREFIX, optional BEDROCK_MODEL

PROFILE="${AWS_PROFILE:?}"
REGION="us-east-1"
STACK="writing-world-backend"
TEMPLATE="$SCRIPT_DIR/backend-stack.yaml"

GREEN='\033[0;32m'; CYAN='\033[0;36m'; NC='\033[0m'
info()    { echo -e "${CYAN}▶ $*${NC}"; }
success() { echo -e "${GREEN}✓ $*${NC}"; }

get_output() {
  aws cloudformation describe-stacks \
    --profile "$PROFILE" --region "$REGION" \
    --stack-name "$STACK" \
    --query "Stacks[0].Outputs[?OutputKey=='$1'].OutputValue" \
    --output text
}

# ── 1. Get the frontend S3 bucket (holds Lambda code) ─────────────────────────
info "Fetching frontend bucket name…"
LAMBDA_BUCKET=$(aws cloudformation describe-stacks \
  --profile "$PROFILE" --region "$REGION" \
  --stack-name writing-world \
  --query "Stacks[0].Outputs[?OutputKey=='BucketName'].OutputValue" \
  --output text)
echo "  Bucket: $LAMBDA_BUCKET"

# ── 2. Package Lambda with strands-agents ─────────────────────────────────────
info "Installing Lambda dependencies…"
PKG_DIR=$(mktemp -d)
pip3 install \
  --requirement "$SCRIPT_DIR/lambda/requirements.txt" \
  --target "$PKG_DIR" \
  --platform manylinux2014_x86_64 \
  --implementation cp \
  --python-version 3.12 \
  --only-binary=:all: \
  --upgrade \
  --quiet

cp "$SCRIPT_DIR/lambda/index.py" "$PKG_DIR/index.py"

info "Zipping Lambda package…"
ZIP_FILE="/tmp/extract-$(date +%s).zip"
(cd "$PKG_DIR" && zip -r "$ZIP_FILE" . -q)
rm -rf "$PKG_DIR"
success "Lambda package ready ($(du -sh "$ZIP_FILE" | cut -f1))."

# ── 3. Upload Lambda ZIP to S3 ─────────────────────────────────────────────────
info "Uploading Lambda package to S3…"
aws s3 cp "$ZIP_FILE" "s3://$LAMBDA_BUCKET/lambda/extract.zip" \
  --profile "$PROFILE"
rm "$ZIP_FILE"
success "Lambda package uploaded."

# ── 4. Deploy CloudFormation ───────────────────────────────────────────────────
PARAM_OVERRIDES="CognitoDomainPrefix=${COGNITO_DOMAIN_PREFIX:?} LambdaBucket=${LAMBDA_BUCKET}"
if [[ -n "${BEDROCK_MODEL:-}" ]]; then
  PARAM_OVERRIDES="$PARAM_OVERRIDES BedrockModel=$BEDROCK_MODEL"
fi

info "Deploying backend stack '$STACK'…"
aws cloudformation deploy \
  --profile "$PROFILE" --region "$REGION" \
  --stack-name "$STACK" \
  --template-file "$TEMPLATE" \
  --capabilities CAPABILITY_NAMED_IAM \
  --parameter-overrides $PARAM_OVERRIDES \
  --no-fail-on-empty-changeset
success "Stack deployed."

# ── 5. Update Lambda code (CloudFormation won't redeploy if S3 key is unchanged) ─
info "Forcing Lambda code update…"
for FN in writing-world-extract writing-world-processor; do
  aws lambda update-function-code \
    --profile "$PROFILE" --region "$REGION" \
    --function-name "$FN" \
    --s3-bucket "$LAMBDA_BUCKET" \
    --s3-key lambda/extract.zip \
    --no-cli-pager &>/dev/null && echo "  ✓ $FN"
done

# ── 6. Fetch outputs and write js/config.js ────────────────────────────────────
info "Fetching stack outputs…"
COGNITO_DOMAIN=$(get_output CognitoDomain)
CLIENT_ID=$(get_output UserPoolClientId)
RAW_API=$(get_output ApiEndpoint)   # https://abc.execute-api.region.amazonaws.com/live

# Extract just the hostname for the CloudFront origin parameter
API_HOSTNAME=$(echo "$RAW_API" | sed 's|https://||' | cut -d'/' -f1)

echo "  Cognito domain: $COGNITO_DOMAIN"
echo "  Client ID:      $CLIENT_ID"
echo "  API hostname:   $API_HOSTNAME"

# ── 6a. Update frontend stack with API origin ─────────────────────────────────
info "Updating frontend CloudFront distribution with API origin…"
aws cloudformation deploy \
  --profile "$PROFILE" --region "$REGION" \
  --stack-name writing-world \
  --template-file "$SCRIPT_DIR/stack.yaml" \
  --no-fail-on-empty-changeset \
  --parameter-overrides ApiGatewayDomain="$API_HOSTNAME"
success "Frontend stack updated."

# In production: API is served same-origin via CloudFront at /api/*
# Stage name is 'api', so CloudFront /api/extract → API GW /api/extract  (no rewrite needed)
# In local dev: call API Gateway directly to bypass CloudFront

info "Writing js/config.js…"
cat > "$APP_DIR/js/config.js" <<EOF
// Generated by deploy-backend.sh — do not edit manually.
export const AUTH_CONFIG = {
  cognitoDomain: '${COGNITO_DOMAIN}',
  clientId:      '${CLIENT_ID}',
  // Same-origin in production (/api/*); direct URL for localhost
  apiEndpoint:   window.location.hostname === 'localhost' ? '${RAW_API}' : '/api',
  redirectUri:   window.location.origin + '/',
};
EOF
success "js/config.js written."

# ── 7. Push updated frontend JS ────────────────────────────────────────────────
info "Syncing frontend…"
bash "$SCRIPT_DIR/deploy.sh" sync

echo ""
success "Backend deployment complete!"
